global:
  scrape_interval:  15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [
          'localhost:9090',
          'node_exporter:9100',
          'cadvisor_exporter:8080'
        ]

remote_write:
  - url: "http://influxdb:8086/api/v1/prom/write?u=prometheus_u&p=prometheus_u_passwd&db=prometheus_db"
remote_read:
  - url: "http://influxdb:8086/api/v1/prom/read?u=prometheus_u&p=prometheus_u_passwd&db=prometheus_db"
